attention_scaling_head:false
attention_scaling_topk:false
batch_size:32
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
cls_loss_weight:0.1
criterion:"proxyanchor"
dataset:"oxford_flowers102"
drop_path:0
dynamic_kmeans:10
early_stop_thr:-1
epochs:100
eval_after:90
fp16:true
head_pooling:"max"
init_divide_by8:true
initial_mapping:"kmeans"
key_patch_emb:false
kmeans_norm:"layer"
last_vpt_gradient_scale:1
loss_vpt_scale_ratio:5
lr:0.001
min_lr:0.00000001
0:"dataset"
1:"num_prompts"
2:"lr"
3:"weight_decay"
norm_norm1:true
num_prompts:40
pooling_type:"mean"
prompt_depth:11
prompt_sample_type:"none"
proxy_vpt:true
query_vpt_emb:true
sched_on_updates:true
select_type:"cls_attn"
topk:1
train_cls:true
tuning_type:"prompt"
vpt_gradient_scale:1
vpt_loss_weight:0.1
vpt_norm:"none"
warmup_epochs:10
warmup_lr:0.0000001
wd_head:3
weight_decay:0.5