batch_size:32
bias_fc2:true
bias_k:false
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
cls_loss_weight:0.5
cls_type:"query"
criterion:"proxyanchor"
dataset:"cars"
drop_path:0
dynamic_kmeans:1
early_stop_thr:-1
epochs:100
eval_after:60
fp16:true
init_divide_by8:false
initial_mapping:"kmeans"
kmeans_norm:"layer"
loss_vpt_scale_ratio:5
lr:0.005
mask:true
min_lr:0.000000001
model_name:"mae-B"
norm_norm1:false
num_prompts:15
open_bias_decay:false
open_weight_decay:false
patch_type:"output"
proxy_prompt_len:15
proxy_prompt_start_idx:4
proxy_vpt:true
sched_on_updates:true
train_cls:false
tuning_type:"prompt"
vpt_loss_stop_thr:-1
vpt_loss_weight:0.01
vpt_norm:"none"
vpt_type_for_cls_ml:"vpt"
vpt_type_for_patch_ml:"vpt"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:0.1
weight_decay:0.05