attention_scaling_head:false
attention_scaling_topk:false
batch_size:32
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
cls_loss_weight:0.02
criterion:"proxyanchor"
dataset:"cub"
drop_path:0.1
dynamic_kmeans:1
early_stop_thr:0.6
epochs:100
eval_after:80
fp16:true
full_patch_negative:false
full_patch_positive:true
head_pooling:"max"
init_divide_by8:true
initial_mapping:"kmeans"
key_patch_emb:false
kmeans_norm:"layer"
loss_vpt_scale_ratio:1
lr:0.005
min_lr:0.000000001
model_name:"moco-B"
norm_norm1:true
num_prompts:40
open_bias_decay:false
open_weight_decay:false
pooling_type:"mean"
proxy_prompt_depth:1
proxy_prompt_len:20
proxy_prompt_start_idx:11
proxy_vpt:true
query_vpt_emb:true
sched_on_updates:true
select_head_composed_patch:true
select_type:"cls_attn"
topk:1
train_cls:true
tuning_type:"prompt"
vpt_loss_stop_thr:-1
vpt_loss_weight:0.1
vpt_norm:"l2"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:0.1
weight_decay:1