attention_scaling_head:false
attention_scaling_topk:false
batch_size:32
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
cls_loss_weight:0.03
criterion:"proxyanchor"
dataset:"dogs"
drop_path:0
dynamic_kmeans:10
epochs:100
eval_after:80
fp16:true
head_pooling:"max"
init_divide_by8:true
initial_mapping:"kmeans"
key_patch_emb:true
kmeans_norm:"layer"
loss_vpt_scale_ratio:5
lr:0.005
min_lr:0.000000001
model_name:"moco-B"
norm_norm1:true
num_prompts:5
pooling_type:"mean"
prompt_sample_type:"none"
proxy_prompt_depth:1
proxy_prompt_len:10
proxy_prompt_start_idx:11
proxy_vpt:true
query_vpt_emb:false
sched_on_updates:true
select_head_composed_patch:true
select_type:"cls_attn"
topk:1
train_cls:true
tuning_type:"prompt"
vpt_loss_weight:0.01
vpt_norm:"none"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:0.05
weight_decay:0.0001