batch_size:32
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
cls_loss_weight:0.05
criterion:"proxyanchor"
dataset:"cars"
dynamic_kmeans:10
early_stop_thr:-1
epochs:100
eval_after:80
fp16:true
head_pooling:"max"
init_divide_by8:true
initial_mapping:"kmeans"
kmeans_norm:"layer"
loss_vpt_scale_ratio:60
lr:0.001
mask:false
min_lr:0.000000001
norm_norm1:true
num_prompts:80
prompt_sample_type:"none"
proxy_prompt_end_idx:11
proxy_prompt_len:60
proxy_prompt_start_idx:11
proxy_vpt:true
sched_on_updates:true
select_type:"cls_attn"
train_cls:true
tuning_type:"prompt"
vpt_loss_stop_thr:0.001
vpt_loss_weight:0.05
vpt_norm:"none"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:3
weight_decay:0.05