attention_scaling_head:false
attention_scaling_topk:false
batch_size:32
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
criterion:"proxyanchor"
dataset:"flowers"
dynamic_kmeans:10
early_stop_thr:-1
epochs:100
eval_after:60
fp16:true
head_pooling:"max"
init_divide_by8:true
initial_mapping:"kmeans"
key_patch_emb:false
kmeans_norm:"layer"
lr:0.001
min_lr:0.000000001
norm_norm1:true
num_last_prompts:20
num_prompts:40
pooling_type:"mean"
prompt_depth:11
prompt_sample_type:"none"
proxy_vpt:true
query_vpt_emb:true
sched_on_updates:true
select_head_composed_patch:true
select_type:"cls_attn"
topk:1
train_cls:true
tuning_type:"prompt"
vpt_and_cls_loss_weight:0.05
vpt_loss_stop_thr:-1
vpt_norm:"none"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:3
weight_decay:0.05