batch_size:32
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
cls_loss_weight:0.05
cls_type:"query"
criterion:"proxyanchor"
dataset:"cub"
drop_path:0.1
dynamic_kmeans:1
early_stop_thr:0.88
epochs:100
eval_after:80
fp16:true
init_divide_by8:true
initial_mapping:"kmeans"
kmeans_norm:"layer"
loss_vpt_scale_ratio:5
lr:0.0005
mask:true
min_lr:0.000000001
norm_norm1:true
num_prompts:10
open_bias_decay:false
open_weight_decay:false
patch_type:"output"
proxy_prompt_end_idx:11
proxy_prompt_len:10
proxy_prompt_start_idx:10
proxy_vpt:true
sched_on_updates:true
train_cls:true
tuning_type:"prompt"
vpt_loss_stop_thr:-1
vpt_loss_weight:0.05
vpt_norm:"l2"
vpt_type_for_cls_ml:"vpt"
vpt_type_for_patch_ml:"vpt"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:5
weight_decay:0.05