attention_scaling_head:false
attention_scaling_topk:false
batch_size:64
bias_fc2:true
bias_k:true
bias_norm2:true
bias_proj:true
bias_q:false
bias_v:true
class_sampler:true
criterion:"proxyanchor"
dataset:"dogs"
drop_path:0
dynamic_kmeans:10
early_stop_thr:0.85
epochs:100
eval_after:80
fp16:true
head_pooling:"max"
init_divide_by8:true
initial_mapping:"kmeans"
key_patch_emb:false
kmeans_norm:"layer"
loss_vpt_scale_ratio:1
lr:0.0002
min_lr:0.000000001
norm_norm1:true
num_last_prompts:5
num_prompts:20
pooling_type:"mean"
prompt_depth:11
prompt_sample_type:"none"
proxy_vpt:true
query_vpt_emb:true
samples_per_class:4
sched_on_updates:true
select_head_composed_patch:true
select_type:"cls_attn"
topk:1
train_cls:true
tuning_type:"prompt"
vpt_and_cls_loss_weight:0.01
vpt_loss_stop_thr:0.001
vpt_norm:"none"
warmup_epochs:10
warmup_lr:0.00000001
wd_head:3
weight_decay:0.05